### ISSUE TITLE
Please make a new git tag when merging a fix

### ISSUE THREAD

**Issue by p0nce** [dlang/undeaD#10]
I stumbled upon #8 but it has been fixed already.

**Comment by MartinNowak** [comment]
Ping @WalterBright, need to `git tag v1.0.6 && git push origin v1.0.6`.
At best you give some more people write access to the repo, so you don't remain the only maintainer.

**Comment by wilzbach** [comment]
> At best you give some more people write access to the repo, so you don't remain the only maintainer.

We could also move the repo over to the dlang organization?

**Comment by WalterBright** [comment]
> need to git tag v1.0.6 && git push origin v1.0.6.

Done.

> We could also move the repo over to the dlang organization?

I'd like to do that. Martin?

**Comment by MartinNowak** [comment]
> I'd like to do that. Martin?

Yes, let's do that @WalterBright. You're the only one who actually has all rights to that.
First make sure that you can login to http://code.dlang.org/my_packages/undead to later change the associated repo.
Then simply go to the danger zone of https://github.com/DigitalMars/undeaD/settings and transfer ownership to dlang.
After that succeeded change the repository owner on the code.dlang.org page.

**Comment by WalterBright** [comment]
Done. Team Phobos has access to it.
