### ISSUE TITLE
Register with travis

### ISSUE THREAD

**Issue by John-Colvin** [dlang/undeaD#11]
see https://travis-ci.org/dlang, undeaD doesn't seem to be there

**Comment by wilzbach** [comment]
Yep I think an admin needs to enable it.

@WalterBright could you flip the switch over at Travis?

https://docs.travis-ci.com/user/for-beginners

**Comment by WalterBright** [comment]
It has a green checkmark beside dlang, so I think it already has access to it.

**Comment by sambrightman** [comment]
There needs to be a green check mark next to undeaD itself. There should be a toggle switch on the profile page of the admin for dlang/undeaD.

<img width="359" alt="sam_brightman_-_profile_-_travis_ci" src="https://cloud.githubusercontent.com/assets/536652/20306445/9388677c-ab3a-11e6-92ba-75f20b9ece4c.png">

**Comment by wilzbach** [comment]
Ping @CyberShadow - would you be so kind to enable this repo at Travis?

**Comment by CyberShadow** [comment]
"Repository has been successfully activated."

**Comment by John-Colvin** [comment]
https://github.com/dlang/undeaD/pull/14
