### ISSUE TITLE
Request v1.0.7 tag

### ISSUE THREAD

**Issue by rwtolbert** [dlang/undeaD#18]

**Comment by tillea** [comment]
Hi,
I guess this request is to make a new release.  This was also suggested by Debian packaging D maintainers when I reported some trouble when packaging undeaD for Debian which is currently in the [Debian new queue](https://ftp-master.debian.org/new/libundead_1.0.6-1.html).  So I agree with the opener of this issue that a new release would be helpful.
Thanks, Andreas.

**Comment by rwtolbert** [comment]
Any chance we can get 1.0.7 pushed for dub? 1.0.6 is from Jun 2016 and we have a number of good fixes since then.

**Comment by wilzbach** [comment]
@CyberShadow @andralex @WalterBright as mentioned via mail a couple of weeks ago: we really need _someone_ as a maintainer for undeaD ...

It seems that I don't have write permissions here, so I can't push the tag for this one. @CyberShadow maybe?

**Comment by CyberShadow** [comment]
I gave write access to the core team, so you should now be able to do that @wilzbach.

**Comment by wilzbach** [comment]
> I gave write access to the core team, so you should now be able to do that @wilzbach.

Hehe, I didn't volunteer for this (and won't have the time), but I can help this issue for now.

@rwtolbert 1.0.7 is now live:

https://github.com/dlang/undeaD/releases/tag/v1.0.7
http://code.dlang.org/packages/undead
