### ISSUE TITLE
undead vs std

### ISSUE THREAD

**Issue by John-Colvin** [dlang/undeaD#3]
Wouldn't it be better to keep the package name as ```std``` to allow old code to use these transparently?

There is some precedent in dub packages containing proposed phobos modules.

**Comment by MartinNowak** [comment]
Agreed, we should change that.

**Comment by WalterBright** [comment]
If the user imports `std.foo`, is it Phobos' `std` or undead's `std`? This seems like trouble.

**Comment by p0nce** [comment]
It would be trouble. Please do not change to  `std.foo`. We can import the right one using __VERSION__

**Comment by MartinNowak** [comment]
Let's close this.

**Comment by John-Colvin** [comment]
agreed
