### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by 0xEAB** [dlang/undeaD#34]
The `delete` keyword has been deprecated for quite a while. In the current release ([v1.0.9](https://github.com/dlang/undeaD/commits/v1.0.9) from 2017) it's still used.

This leads to such funky warnings (which affects basically all DUB packages depending on *undeaD*):
```d
../../.dub/packages/undead-1.0.9/undead/src/undead/regexp.d(939,9): Deprecation: The delete keyword has been deprecated.  Use object.destroy() (and core.memory.GC.free() if applicable) instead.
```

It would be nice to have a new release featuring #32.

**Comment by ZombineDev** [comment]
Hi @0xEAB! I just tagged v1.0.10: https://github.com/dlang/undeaD/releases/tag/v1.0.10, which I believe should solve the problems you were experiencing.

**Comment by 0xEAB** [comment]
neat :tada:  thanks
