### ISSUE TITLE
Deprecations: opCatAssign and format specification (dmd 2.093.0)

### ISSUE THREAD

**Issue by andre2007** [dlang/undeaD#40]
undead-1.1.1 throws these deprecations with dmd 2.093.0:

>/home/user/.dub/packages/undead-1.1.1/undead/src/undead/bitarray.d(907,11): Deprecation: opCatAssign is deprecated.  Use opOpAssign(string op)(...) if (op == "~") instead.
>/home/user/.dub/packages/undead-1.1.1/undead/src/undead/date.d(690,35): Deprecation: argument cast(long)yearFromTime(t) for format specification "%d" must be int, not long
>/home/user/.dub/packages/undead-1.1.1/undead/src/undead/date.d(751,31): Deprecation: argument cast(long)yearFromTime(t) for format specification "%d" must be int, not long

**Comment by wilzbach** [comment]
Once fixed, we should probably add `-de` as a flag for undead to the Buildkite tester.

https://github.com/dlang/ci/blob/master/buildkite/build_project.sh

**Comment by PetarKirov** [comment]
Fixed as of #41 and #42. [Release `v1.1.3`](https://github.com/dlang/undeaD/releases/tag/v1.1.3) tagged and published.

**Comment by andre2007** [comment]
@PetarKirov thanks:)
