### ISSUE TITLE
doformat should be completely disabled for GDC

### ISSUE THREAD

**Issue by schveiguy** [dlang/undeaD#55]
Located inside doformat is a use of `va_arg` with the `TypeInfo` form. According to the [GCC project](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108763), and [druntime](https://github.com/dlang/dmd/blob/650b75b7c19a3e9fd8c8645ac538f8e08bedc733/druntime/src/core/vararg.d#L22), GDC does not and will not support this feature.

What this means is that anyone wishing to use the `undead` project with GDC will face compilation errors *even if they never use doformat*.

I propose that doFormat be versioned out for GNU just like the va_arg function it depends on. At least then, people can use the other parts of undead without dealing with unrelated compilation failures.

**Comment by ibuclaw** [comment]
Agreed.  There is no reasonable way to support this.
